(defparameter *descriptions*
  '(
    (OUI . "Oui.")
    (NON . "Non.")
    (RESOUDREPROBMATH . "Je souhaite résoudre un problème mathématique.")
    (MODELISER . "Je souhaite modéliser un problème.")
    (MODELISERDONNEE . "Je souhaite modéliser un problème basée sur des données.")
    (MODELISERSYSTEMECOMPLEXE . "Je souhaite modéliser un système complexe.")
    (JEUX . "Oui j'aime les jeux")
    (DECOUVRIR . "Je souhaite découvrir des choses.")
    (MISEENFORMEINFOS . "Je souhaite mettre en forme de l'information.")
    (TRAITEMENTDINFOS . "Je souhaite traiter de l'information.")
    (APPRENTISSAGE . "Je veux apprendre un langage de programmation.")
    (SCIENTIFIQUE . "Le travail a un aspect scientifique et/ou académique.")
    (PASFORCEMENT . "Hmmm ... pas forcément.")
    (COLLABORATIF . "Je souhaite que celui-ci soit collaboratif.")
    (REDACTION . "C'est un travail de rédaction.")
    (EXPRESSION-REGULIERE . "Je souhaite utiliser des expression régulière.")
    (GRAPHE . "Je souhaite représenter les données sous forme de graphe.")
    (DOCUMENT . "Je souhaite représenter les données sous forme de document.")
    (NOSQL . "L'usage de la BDD est tournée vers le NoSQL.")
    (PRIVE . "Je souhaite en faire un usage privé.")
    (PREFERE . "Que préférez-vous entre les jeux PC et les jeux smartphone ?")
    (CONTROLEACCES . "Avez-vous besoin de contrôler l'accès de différents utilisateurs sur cette plateforme ?")
    (BEAUCOUPINFO . "Disposez-vous de beaucoup d'informations ? ")
    (GRANDPUBLIC . "Je souhaite en faire un usage grand-public.")
    (RELATIONNEL . "L'usage de la BDD est tournée vers le NoSQL.")
    (DATAWARE . "Je souhaite traiter de vaste-ensemble de données.")
    (AUTRE . "Non, je veux faire autre choses avec les SMA.")
    (TRADING . "Je veux faire du trading, et/ou utiliser des technologies adaptées à la finance.")
    (SIMULATIONDEFOULE . "Je voudrais simuler le comportement de foule lors d'un évènement particulier.")
    (SMA . "Je veux utiliser des SMA.")
    (SYSTEME-EMBARQUE . "Je veux programmer un système embarqué.")
    (INTERACTION . "Je souhaite créer des fenêtres d'interactions entre l'utilisateur et la machine.")
    (SYSTEME . "Je souhaite définir des processus dans le système et/ou parametrer au mieux ma machine, planifier des tâches ...")
    (DIY . "Je veux bricoler un truc electronique.")
    (LINUX . "Cela a pour visée Linux.")
    (2D . "Mon jeu sera un jeu 2D.")
    (RPG-2D . "Mon jeu sera un RPG-2D.")
    (3D . "Le joueur évoluera dans un environnement 3D.")
    (JEU-VIDEO . "Je veux dévelloper un jeu-vidéo !")
    (APPLET . "Je veux faire une petite application.")
    (NON-SUPPORTEE . "Non ... je ne supporte pas trop les parenthèses.")
    (SUPPORTEE . "Oui, cela ne me pose pas trop de problème.")
    (SYSTEME-EXPERT . "Je veux faire un système-expert.")
    (MODELE-COMPLEXE . "Je veux modéliser un phénomène ou une situation complexe.")
    (PROTOTYPAGE-RAPIDE . "Je veux rapidement avoir quelque chose de fonctionnel et/ou d'expérimental et/ou facilement modifiable.")
    (MACHINE-LEARNING . "Je préfère des méthodes d'apprentissage statistiques.")
    (CALCUL-FORMEL . "Je veux résoudre ce problème de manière formelle.")
    (INDIVIDUEL . "J'en ferrai une utilisation personnelle.")
    (CALCUL-NUMERIQUE . "Je veux résoudre ce problème par des méthode numériques.")
    (NUMERIQUE . "Je veux résoudre ce problème par des méthode numériques.")
    (FORMELLE . "Je veux résoudre ce problème formellement.")
    (WINDOWS . "Cela a pour visée un environnement Windows.")
    (COMPLEXE . "Le document est un travail important.")
    (LOGICIEL . "Je veux développer un logiciel.")
    (ANDROID . "Je veux développer des app Android.")
    (IPHONE . "Je veux développer des app iPhone.")
    (MAC . "Je travaille sur un Mac.")
    (MOBILE . "Je veux développer des applications smartphone.")
    (POPULAIRE . "Je préfère une solution populaire chez les développeur avec une grand communauté.")
    (CONFIGURABLE . "Je préfère une solution configurable où l'on peut comprendre et modifier à peu près tout.")
    (EFFICACE . "Je veux faire site web d'une taille concéquante avec beaucoup d'utilisateurs l'utilisant.")
    (RESPONSIVE . "Je veux faire un site web qui s'adapte bien à tout types d'appareil.")
    (SIMPLE . "Je veux un site web simple et fonctionnel ; pas besoin qu'il soit spécialement beau.")
    (BONNE . "Je veux un site web simple à mettre en place et d'assez bonne facture.")
    (SITE-WEB . "Je veux faire un site-web.")
    (FAIREDESMODELES . "Je veux faire des modèles prédictifs et/ou d'apprentissage sur ces données")
    (ORGANISER . "Je souhaite organiser cette information.")
    (FILTRERTEXTE . "Je veux chercher des informations spécifiques dans un ensemble de données textuelles éventuellement grand.")
    (PCETCONSOLES . "Je préfère les jeux PC et consoles.")
    (SMARTPHONE . "Je préfère les jeux sur smartphone.")
    (EQUATIONS . "Je veux résoudre des équations.")
    (SYMBOLIQUE . "Je préfère utilisée une intelligence artificielle symbolique.")
    (INTERACTIONSYS . "Je veux simuler les interractions qu'il peut y avoir dans un système complexe.")))
