(defun init (choix)
  (let (path)
  (if (= choix 1)
    (setq path "~/Cloud/WORK/UTC/GI01/IA01/Cactus/")
    (setq path "~/Documents/UTC/GI01/IA01/Cactus/"))
  (load (concatenate 'string path "technologies.lisp"))
  (load (concatenate 'string path "regles.lisp"))
  (load (concatenate 'string path "questions.lisp"))
  (load (concatenate 'string path "fonctionsOutilsFaits.lisp"))
  (load (concatenate 'string path "fonctionsOutilsRegles.lisp"))
  (load (concatenate 'string path "chainageAvantLarg.lisp"))
  (load (concatenate 'string path "chainageAvantProf.lisp"))
  (load (concatenate 'string path "askQuestion.lisp"))
  (load (concatenate 'string path "afficherPropositions.lisp"))
  (load (concatenate 'string path "intro.lisp"))
  (defparameter *faits* nil)
  (intro)
  (ChainageAvantLarg)
))

;examples:
;(init "~/Cloud/WORK/UTC/GI01/IA01/Cactus/")
