(defparameter *regles* '(
	; Règles construites de la fonctions suivantes :
	;
	; (((Premisse1 opérateur valeur)...(PremisseN opérateur valeur))
	;  	((Résultat1 opérateur valeur)...(Résultat1M opérateur valeur)))

	;; Affichage s'il y a des propositions
	;;; Propositions Finales
	(((Application EQ Site-Web-Simple))
		((Propositions EQ (PHP MySQL))))
	(((Application EQ Site-Web-Responsive))
		((Propositions EQ (PHP MySQL BootStrap JavaScript))))
	(((Application EQ Site-Web-Efficace))
		((Propositions EQ (Django))))
	(((Application EQ Site-Web-Efficace))
		((Propositions EQ (Ruby-on-Rails))))
	(((Application EQ Site-Web-Simple))
		((Propositions EQ (PHP MySQL))))
	(((Application EQ Mobile) (Machine EQ Mac))
		((Propositions EQ (Swift)))) ;TODO : Choisir 1
	(((Application EQ Mobile)(Machine EQ Mac)(Cible EQ iPhone) (Budget > 100))
		((Propositions EQ (Swift)))) ;TODO : Choisir 2
	(((Application EQ Mobile) (Cible EQ Android))
		((Propositions EQ (JAVA Android-Studio SDK-Android))))
	(((Application EQ Logiciel) (Precision EQ Solide))
		((Propositions EQ (C++ JAVA))))
	(((Application EQ Logiciel) (Precision EQ Solide) (Machine EQ Windows))
		((Propositions EQ (C#))))
	(((Application EQ Systeme-Expert) (Parenthèse EQ Supportee))
		((Propositions EQ (LISP))))
	(((Application EQ Systeme-Expert) (Parenthèse EQ Non-Supportee))
		((Propositions EQ (Prolog))))
	(((Application EQ Applet) (Usage EQ Personnel))
		((Propositions EQ (Pygame Tkinter))))
	(((Application EQ Systeme) (Machine EQ Linux) (Precision EQ Interaction))
		((Propositions EQ (C Shell Tkinter))))
	(((Application EQ Jeu-Vidéo) (Precision EQ 3D))
		((Propositions EQ (C++ Unity3D))))
	(((Application EQ DIY))
		((Propositions EQ (Arduino))))
	(((Application EQ DIY) (Precision EQ Internet))
		((Propositions EQ (Raspberry-Pi))))
	(((Application EQ Systeme-Embarque))
		((Propositions EQ (Assembleur))))
))
