(defparameter *technologies*
	'(
		(C . "Un des langages les plus populaires et très bien structuré ; utilisé pour accéder à la mémoire de la machine, pour la création de système d'exploitation.")
		(C++ . "Inspiré du C, il en reprend beaucoup de spécificités et est orienté programmation objet.")
			(QtScript . "A COMPLETER")
		(Python . "Langage interprété de prototypage. Efficace et très simple d'utilisation ; de nombreuses bibliothèques.")
			(Tkinter . "Bibliothèque Python : permet de créer des interfaces graphiques.")
			(PyGame . "Bibliothèque Python : permet de créer des petits jeux et applications graphiques.")
			(Django . "FrameWork de développement web Python : très bien construit et extremement efficace une fois maîtrisé 'Django : the web framework for perfectionists with deadlines'.")
			(Numpy-MathPlotLib . "Bibliothèque python : boîte à outils scientifiques")
			(Sci-kit . "Bibliothèque python : boîte à outils scientifiques")
		(Ruby . "A COMPLETER")
			(Ruby-on-Rails . "A COMPLETER")
		(R . "Utilisé dans les domaines scientifiques (particulièrement en statistiques et data-mining)")
		(MatLab . "A COMPLETER")
		(Octave . "A COMPLETER")
		(LISP . "(((((((((((((((((((((lel)))))))))))))))))))))")
		(Scheme . "A COMPLETER")
		(Pascal . "Un langage de programmation ancien; sa synthaxe est simple ce qui lui donne un bon atout pédagogique.")
		(Prolog . "Un langage de programmation français (Cocorico !), il est utilisé en Intelligence Artificielle")
		(Scala . "A COMPLETER")
		(SQL . "Le standard des bases de données relationnelles : c'est à la fois un langage et une technologies d'implémenation de BDD ; connait plusieurs variantes d'implémentations")
			(PL/SQL . "Variante propriétaire d'Oracle ; permet d'implémenter des bases de données relationnelles-objet et dispose de fonctions et fonctionnalités supplémentaires.")
			(PostGreSQL . "Variantes libre d'implémentation de SQL la plus populaire.")
			(MySQL . "Variantes libre d'implémentation de SQL, simple d'utilisation mais aussi moins bien structurée.")
		(VBA . "A COMPLETER")
		(Arduino . "A COMPLETER")
		(HTML . "Formalisme de représentation de données utilisée par les pages web. La base du développement web")
			(JavaScript . "Langage de programmation permettant de faire fonctionner des applications web côté client.")
			(Json . "Un formalisme récent de représentation simple et lisible d'informations ; standard utilisé par beaucoup de langages.")
			(XML . "Un formalisme plus ancien de représentation simple et lisible d'informations ; standard utilisé par beaucoup de langages.")
		(Swift . "Un langage de programmation d'Apple pour développer des applications iPhone")
		(Objective-C . "Un langage de programmation d'Apple pour développer des applications iPhone")
		(C# . "Le langage de programmation orientée objet de Microsoft. Il révèle tout son potentiel s'il est utilisé conjointement au framework.NET")
		(Java . "Le langage de programmation orientée objet")
			(NodeJS . "A COMPLETER")
			(AJAX . "A COMPLETER")
		(Neo4J . "Technologie NoSQL : données représentées sous forme de graphes.")
		(MongoDB . "Technologie NoSQL : données non structurées stockées sous le formalisme JSON")
		(Cansadra . "Technologie NoSQL : A COMPLETER")
		(PHP . "Le langage de developpement web le plus utilisé : s'exécute côté serveur.")
			(Symfony . "Sûrement le framework PHP le plus populaire : formalisme Modèle-Vue-Contrôleur")
		(Fortran . "Vieux langage de programmation utilisé pour le calcul scientifique")
		(INTERCAL . "A COMPLETER")
		(Basic . "A COMPLETER")
		(Scilab . "Logiciel et langage de programmation de calcul numérique, alternative libre à Matlab.")
		(Julia . "Logiciel et langage de programmation de calcul numérique, alternative récente et libre à Matlab. Performant.")
		(LaTeX . "Langage et un système de composition de documents. Utilisé pour la rédaction de documents scientifique. Beaucoup de bibliothèque (package)")
		(Go . "Langage de programmation de Google ; se veut efficace et simple d'apprentissage.")
		(Maple . "A COMPLETER")
		(Sage . "A COMPLETER")
		(Perl . "A COMPLETER")
		(LolCat . "LOL U RLY NEEDIT")
		(Piet . "ou l'art de coder.")
		(WhiteSpace . "A COMPLETER")
		(Shell . "Interpréteur de commandes : l'interface entre l'OS et l'utilisateur")
		(Brainfuck . "Pour le mindfuck")
		(LOLCODE . "Pour troller")
		)
)
